package assignments;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class bookTicket {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void assignment() {
        driver.get("http://newtours.demoaut.com/");
        driver.manage().window().setSize(new Dimension(1382, 744));
        driver.findElement(By.name("userName")).click();
        driver.findElement(By.name("password")).sendKeys("123456");
        driver.findElement(By.name("userName")).sendKeys("gautha551");
        driver.findElement(By.name("login")).click();
        assertThat(driver.getTitle(), is("Find a Flight: Mercury Tours:"));
        driver.findElement(By.name("findFlights")).click();
        assertThat(driver.getTitle(), is("Select a Flight: Mercury Tours"));
        driver.findElement(By.name("reserveFlights")).click();
        driver.findElement(By.name("passFirst0")).click();
        driver.findElement(By.name("passFirst0")).sendKeys("Gautham");
        driver.findElement(By.name("passLast0")).sendKeys("Raju");
        driver.findElement(By.name("creditnumber")).click();
        driver.findElement(By.name("creditnumber")).sendKeys("325642386732");
        driver.findElement(By.name("cc_exp_dt_mn")).click();
        driver.findElement(By.cssSelector("td:nth-child(3) > select:nth-child(1) > option:nth-child(12)")).click();
        driver.findElement(By.name("cc_exp_dt_yr")).click();

        driver.findElement(By.cssSelector("td:nth-child(3) > select:nth-child(2) > option:nth-child(12)")).click();
        driver.findElement(By.name("cc_frst_name")).click();
        driver.findElement(By.name("cc_frst_name")).sendKeys("Gautham");
        driver.findElement(By.name("cc_mid_name")).sendKeys("Raju");
        driver.findElement(By.name("cc_last_name")).sendKeys("N");
        driver.findElement(By.name("buyFlights")).click();
        driver.findElement(By.cssSelector("tr:nth-child(3) p")).click();
        assertThat(driver.findElement(By.cssSelector("p > font font:nth-child(2)")).getText(), is("Your itinerary has been booked!"));
        driver.close();
    }
}
